<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>24 Correspondence Analysis | Statisics for Archaeologists…with R!</title>
  <meta name="description" content="24 Correspondence Analysis | Statisics for Archaeologists…with R!" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="24 Correspondence Analysis | Statisics for Archaeologists…with R!" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="24 Correspondence Analysis | Statisics for Archaeologists…with R!" />
  
  
  

<meta name="author" content="Daniel A. Contreras" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cluster-analysis-ch.html"/>
<link rel="next" href="what-next.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="batches-of-numbers-ch.-1.html"><a href="batches-of-numbers-ch.-1.html"><i class="fa fa-check"></i><b>1</b> Batches of Numbers (Ch. 1)</a>
<ul>
<li class="chapter" data-level="1.1" data-path="batches-of-numbers-ch.-1.html"><a href="batches-of-numbers-ch.-1.html#import-the-scraper-data."><i class="fa fa-check"></i><b>1.1</b> Import the Scraper data.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-level-or-center-of-a-batch-ch.-2.html"><a href="the-level-or-center-of-a-batch-ch.-2.html"><i class="fa fa-check"></i><b>2</b> The Level or Center of a Batch (Ch. 2)</a></li>
<li class="chapter" data-level="3" data-path="the-spread-or-dispersion-of-a-batch-ch.-3.html"><a href="the-spread-or-dispersion-of-a-batch-ch.-3.html"><i class="fa fa-check"></i><b>3</b> The Spread or Dispersion of a Batch (Ch. 3)</a></li>
<li class="chapter" data-level="4" data-path="comparing-batches-ch.-4.html"><a href="comparing-batches-ch.-4.html"><i class="fa fa-check"></i><b>4</b> Comparing Batches (Ch. 4)</a></li>
<li class="chapter" data-level="5" data-path="the-shape-or-distribution-of-a-batch-ch.-5.html"><a href="the-shape-or-distribution-of-a-batch-ch.-5.html"><i class="fa fa-check"></i><b>5</b> The Shape or Distribution of a Batch (Ch. 5)</a></li>
<li class="chapter" data-level="6" data-path="categories-ch.-6.html"><a href="categories-ch.-6.html"><i class="fa fa-check"></i><b>6</b> Categories (Ch. 6)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="categories-ch.-6.html"><a href="categories-ch.-6.html#practice"><i class="fa fa-check"></i><b>6.1</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="samples-and-populations-ch.-7.html"><a href="samples-and-populations-ch.-7.html"><i class="fa fa-check"></i><b>7</b> Samples and Populations (Ch. 7)</a></li>
<li class="chapter" data-level="8" data-path="different-samples-from-the-same-population-ch.-8.html"><a href="different-samples-from-the-same-population-ch.-8.html"><i class="fa fa-check"></i><b>8</b> Different Samples from the Same Population (Ch. 8)</a></li>
<li class="chapter" data-level="9" data-path="confidence-and-population-means-ch.-9.html"><a href="confidence-and-population-means-ch.-9.html"><i class="fa fa-check"></i><b>9</b> Confidence and Population Means (Ch. 9)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="confidence-and-population-means-ch.-9.html"><a href="confidence-and-population-means-ch.-9.html#students-t"><i class="fa fa-check"></i><b>9.1</b> Student’s <em>t</em></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="resampling.html"><a href="resampling.html"><i class="fa fa-check"></i><b>10</b> Medians and Resampling (Ch. 10)</a></li>
<li class="chapter" data-level="11" data-path="categories-and-population-proportions-ch.-11.html"><a href="categories-and-population-proportions-ch.-11.html"><i class="fa fa-check"></i><b>11</b> Categories and Population Proportions (Ch. 11)</a></li>
<li class="chapter" data-level="12" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html"><i class="fa fa-check"></i><b>12</b> Comparing Two Sample Means (Ch. 12)</a>
<ul>
<li class="chapter" data-level="12.1" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html#confidence-significance-and-strength"><i class="fa fa-check"></i><b>12.1</b> Confidence, Significance, and Strength</a></li>
<li class="chapter" data-level="12.2" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html#comparison-by-t-test"><i class="fa fa-check"></i><b>12.2</b> Comparison by <em>t</em> Test</a></li>
<li class="chapter" data-level="12.3" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>12.3</b> The One-Sample <em>t</em> Test</a></li>
<li class="chapter" data-level="12.4" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html#assumptions-and-robust-methods"><i class="fa fa-check"></i><b>12.4</b> Assumptions and Robust Methods</a></li>
<li class="chapter" data-level="12.5" data-path="comparing-two-sample-means-ch.-12.html"><a href="comparing-two-sample-means-ch.-12.html#practice-1"><i class="fa fa-check"></i><b>12.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html"><i class="fa fa-check"></i><b>13</b> Comparing Means of More Than Two Samples (Ch. 13)</a>
<ul>
<li class="chapter" data-level="13.1" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html#comparison-with-estimated-means-and-error-ranges"><i class="fa fa-check"></i><b>13.1</b> Comparison with Estimated Means and Error Ranges</a></li>
<li class="chapter" data-level="13.2" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html#comparison-by-analysis-of-variance"><i class="fa fa-check"></i><b>13.2</b> Comparison by Analysis of Variance</a></li>
<li class="chapter" data-level="13.3" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html#differences-between-populations-versus-relationships-between-variables"><i class="fa fa-check"></i><b>13.3</b> Differences between Populations versus Relationships between Variables</a></li>
<li class="chapter" data-level="13.4" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html#assumptions-and-robust-methods-1"><i class="fa fa-check"></i><b>13.4</b> Assumptions and Robust Methods</a></li>
<li class="chapter" data-level="13.5" data-path="comparing-means-of-more-than-two-samples-ch.-13.html"><a href="comparing-means-of-more-than-two-samples-ch.-13.html#practice-2"><i class="fa fa-check"></i><b>13.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html"><i class="fa fa-check"></i><b>14</b> Comparing Proportions of Different Samples (Ch. 14)</a>
<ul>
<li class="chapter" data-level="14.1" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#comparison-with-estimated-proportions-and-error-ranges"><i class="fa fa-check"></i><b>14.1</b> Comparison with Estimated Proportions and Error Ranges</a></li>
<li class="chapter" data-level="14.2" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#comparison-with-chi2"><i class="fa fa-check"></i><b>14.2</b> Comparison with <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="14.3" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#measures-of-strength"><i class="fa fa-check"></i><b>14.3</b> Measures of Strength</a></li>
<li class="chapter" data-level="14.4" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#the-effect-of-sample-size"><i class="fa fa-check"></i><b>14.4</b> The Effect of Sample Size</a></li>
<li class="chapter" data-level="14.5" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#differences-between-populations-versus-relationships-between-variables-1"><i class="fa fa-check"></i><b>14.5</b> Differences between Populations versus Relationships between Variables</a></li>
<li class="chapter" data-level="14.6" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#assumptions-and-robust-methods-2"><i class="fa fa-check"></i><b>14.6</b> Assumptions and Robust Methods</a></li>
<li class="chapter" data-level="14.7" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#comparing-proportions-to-a-theoretical-expectation"><i class="fa fa-check"></i><b>14.7</b> Comparing Proportions to a Theoretical Expectation</a></li>
<li class="chapter" data-level="14.8" data-path="comparing-proportions-of-different-samples-ch.-14.html"><a href="comparing-proportions-of-different-samples-ch.-14.html#practice-3"><i class="fa fa-check"></i><b>14.8</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="relating-a-measurement-variable-to-another-measurement-variable-ch.-15.html"><a href="relating-a-measurement-variable-to-another-measurement-variable-ch.-15.html"><i class="fa fa-check"></i><b>15</b> Relating a Measurement Variable to Another Measurement Variable (Ch. 15)</a>
<ul>
<li class="chapter" data-level="15.1" data-path="relating-a-measurement-variable-to-another-measurement-variable-ch.-15.html"><a href="relating-a-measurement-variable-to-another-measurement-variable-ch.-15.html#practice-4"><i class="fa fa-check"></i><b>15.1</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="relating-ranks-ch.-16.html"><a href="relating-ranks-ch.-16.html"><i class="fa fa-check"></i><b>16</b> Relating Ranks (Ch. 16)</a>
<ul>
<li class="chapter" data-level="16.1" data-path="relating-ranks-ch.-16.html"><a href="relating-ranks-ch.-16.html#calculating-spearmans-rank-correlation-rho"><i class="fa fa-check"></i><b>16.1</b> Calculating Spearman’s Rank Correlation (<span class="math inline">\(\rho\)</span>)</a></li>
<li class="chapter" data-level="16.2" data-path="relating-ranks-ch.-16.html"><a href="relating-ranks-ch.-16.html#significance"><i class="fa fa-check"></i><b>16.2</b> Significance</a></li>
<li class="chapter" data-level="16.3" data-path="relating-ranks-ch.-16.html"><a href="relating-ranks-ch.-16.html#assumptions-and-robust-methods-3"><i class="fa fa-check"></i><b>16.3</b> Assumptions and Robust Methods</a></li>
<li class="chapter" data-level="16.4" data-path="relating-ranks-ch.-16.html"><a href="relating-ranks-ch.-16.html#practice-5"><i class="fa fa-check"></i><b>16.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="sampling-a-population-with-subgroups-ch.-17.html"><a href="sampling-a-population-with-subgroups-ch.-17.html"><i class="fa fa-check"></i><b>17</b> Sampling a Population with Subgroups (Ch. 17)</a>
<ul>
<li class="chapter" data-level="17.1" data-path="sampling-a-population-with-subgroups-ch.-17.html"><a href="sampling-a-population-with-subgroups-ch.-17.html#pooling-estimates"><i class="fa fa-check"></i><b>17.1</b> Pooling Estimates</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="sampling-a-site-or-region-with-spatial-units-ch.-18.html"><a href="sampling-a-site-or-region-with-spatial-units-ch.-18.html"><i class="fa fa-check"></i><b>18</b> Sampling a Site or Region with Spatial Units (Ch. 18)</a>
<ul>
<li class="chapter" data-level="18.1" data-path="sampling-a-site-or-region-with-spatial-units-ch.-18.html"><a href="sampling-a-site-or-region-with-spatial-units-ch.-18.html#estimating-population-proportions"><i class="fa fa-check"></i><b>18.1</b> Estimating Population Proportions</a></li>
<li class="chapter" data-level="18.2" data-path="sampling-a-site-or-region-with-spatial-units-ch.-18.html"><a href="sampling-a-site-or-region-with-spatial-units-ch.-18.html#estimating-population-means"><i class="fa fa-check"></i><b>18.2</b> Estimating Population Means</a></li>
<li class="chapter" data-level="18.3" data-path="sampling-a-site-or-region-with-spatial-units-ch.-18.html"><a href="sampling-a-site-or-region-with-spatial-units-ch.-18.html#densities"><i class="fa fa-check"></i><b>18.3</b> Densities</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="sampling-without-finding-anything-ch.-19.html"><a href="sampling-without-finding-anything-ch.-19.html"><i class="fa fa-check"></i><b>19</b> Sampling without Finding Anything (Ch. 19)</a>
<ul>
<li class="chapter" data-level="19.1" data-path="sampling-without-finding-anything-ch.-19.html"><a href="sampling-without-finding-anything-ch.-19.html#problem-set"><i class="fa fa-check"></i><b>19.1</b> Problem Set</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="sampling-without-finding-anything-ch.-19.html"><a href="sampling-without-finding-anything-ch.-19.html#rework-questions"><i class="fa fa-check"></i><b>19.1.1</b> rework questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html"><i class="fa fa-check"></i><b>20</b> Similarities Between Cases (Ch. 22)</a>
<ul>
<li class="chapter" data-level="20.1" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#euclidean-distance"><i class="fa fa-check"></i><b>20.1</b> Euclidean Distance</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#euclidean-distance-with-standardized-variables"><i class="fa fa-check"></i><b>20.1.1</b> Euclidean Distance with Standardized Variables</a></li>
<li class="chapter" data-level="20.1.2" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#when-to-use-euclidean-distance"><i class="fa fa-check"></i><b>20.1.2</b> When To Use Euclidean Distance</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#presenceabsence-variables-simple-matching-and-jaccards-coefficients-of-similarity"><i class="fa fa-check"></i><b>20.2</b> Presence/Absence Variables: Simple Matching and Jaccard’s Coefficients of Similarity</a></li>
<li class="chapter" data-level="20.3" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#mixed-variables-gowers-coefficient"><i class="fa fa-check"></i><b>20.3</b> Mixed Variables: Gower’s Coefficient</a></li>
<li class="chapter" data-level="20.4" data-path="similarities-between-cases-ch.-22.html"><a href="similarities-between-cases-ch.-22.html#problem-set-1"><i class="fa fa-check"></i><b>20.4</b> Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="multidimensional-scaling-ch.html"><a href="multidimensional-scaling-ch.html"><i class="fa fa-check"></i><b>21</b> Multidimensional Scaling (Ch.23)</a>
<ul>
<li class="chapter" data-level="21.1" data-path="multidimensional-scaling-ch.html"><a href="multidimensional-scaling-ch.html#configurations-in-different-numbers-of-dimensions"><i class="fa fa-check"></i><b>21.1</b> Configurations in Different Numbers of Dimensions</a></li>
<li class="chapter" data-level="21.2" data-path="multidimensional-scaling-ch.html"><a href="multidimensional-scaling-ch.html#interpreting-the-configuration"><i class="fa fa-check"></i><b>21.2</b> Interpreting the Configuration</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="principal-components-analysis-ch.html"><a href="principal-components-analysis-ch.html"><i class="fa fa-check"></i><b>22</b> Principal Components Analysis (Ch.24)</a>
<ul>
<li class="chapter" data-level="22.1" data-path="principal-components-analysis-ch.html"><a href="principal-components-analysis-ch.html#correlations-and-variables"><i class="fa fa-check"></i><b>22.1</b> Correlations and Variables</a></li>
<li class="chapter" data-level="22.2" data-path="principal-components-analysis-ch.html"><a href="principal-components-analysis-ch.html#carrying-out-the-analysis"><i class="fa fa-check"></i><b>22.2</b> Carrying Out the Analysis</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html"><i class="fa fa-check"></i><b>23</b> Cluster Analysis (Ch.25)</a>
<ul>
<li class="chapter" data-level="23.1" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#single-linkage-clustering"><i class="fa fa-check"></i><b>23.1</b> Single Linkage Clustering</a></li>
<li class="chapter" data-level="23.2" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#complete-linkage-clustering"><i class="fa fa-check"></i><b>23.2</b> Complete Linkage Clustering</a></li>
<li class="chapter" data-level="23.3" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#average-linkage-clustering"><i class="fa fa-check"></i><b>23.3</b> Average Linkage Clustering</a></li>
<li class="chapter" data-level="23.4" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#clustering-the-ixcaquixtla-household-data"><i class="fa fa-check"></i><b>23.4</b> Clustering the Ixcaquixtla Household Data</a></li>
<li class="chapter" data-level="23.5" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#clustering-by-variables"><i class="fa fa-check"></i><b>23.5</b> Clustering by Variables</a></li>
<li class="chapter" data-level="23.6" data-path="cluster-analysis-ch.html"><a href="cluster-analysis-ch.html#problem-set-2"><i class="fa fa-check"></i><b>23.6</b> Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="correspondence-analysis.html"><a href="correspondence-analysis.html"><i class="fa fa-check"></i><b>24</b> Correspondence Analysis</a>
<ul>
<li class="chapter" data-level="24.1" data-path="correspondence-analysis.html"><a href="correspondence-analysis.html#an-archaeological-case-study-danish-bronze-age-hoards"><i class="fa fa-check"></i><b>24.1</b> An Archaeological Case Study: Danish Bronze Age Hoards</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="what-next.html"><a href="what-next.html"><i class="fa fa-check"></i><b>25</b> What next?</a>
<ul>
<li class="chapter" data-level="25.1" data-path="what-next.html"><a href="what-next.html#data-wrangling-and-visualization"><i class="fa fa-check"></i><b>25.1</b> Data wrangling and visualization</a></li>
<li class="chapter" data-level="25.2" data-path="what-next.html"><a href="what-next.html#other-analytical-approaches"><i class="fa fa-check"></i><b>25.2</b> Other analytical approaches</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="what-next.html"><a href="what-next.html#bayesian-approaches"><i class="fa fa-check"></i><b>25.2.1</b> Bayesian Approaches</a></li>
<li class="chapter" data-level="25.2.2" data-path="what-next.html"><a href="what-next.html#model-fitting"><i class="fa fa-check"></i><b>25.2.2</b> Model Fitting</a></li>
<li class="chapter" data-level="25.2.3" data-path="what-next.html"><a href="what-next.html#mcmc"><i class="fa fa-check"></i><b>25.2.3</b> MCMC</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="what-next.html"><a href="what-next.html#others"><i class="fa fa-check"></i><b>25.3</b> Others?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><em>Statisics for Archaeologists</em>…with <strong>R</strong>!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correspondence-analysis" class="section level1 hasAnchor" number="24">
<h1><span class="header-section-number">24</span> Correspondence Analysis<a href="correspondence-analysis.html#correspondence-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Drennan does not cover correspondence analysis, but because archaeologists are so likely to work with categorical data, it’s useful to be familiar with this method. This section is based on Ch.13 of Shennan’s <em>Quantifying Archaeology</em> (<span class="citation">Shennan (1997)</span>).</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="correspondence-analysis.html#cb583-1" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb583-2"><a href="correspondence-analysis.html#cb583-2" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb583-3"><a href="correspondence-analysis.html#cb583-3" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb583-4"><a href="correspondence-analysis.html#cb583-4" tabindex="-1"></a><span class="fu">library</span>(Ternary)</span>
<span id="cb583-5"><a href="correspondence-analysis.html#cb583-5" tabindex="-1"></a><span class="fu">library</span>(ca)</span></code></pre></div>
<p>PCA and MDS give us tools for considering multivariate data in all their glory - but based as they are on correlations between <em>measurement</em> variables, these tools are less than ideal for categorical variables or presence/absence variables.</p>
<p>Recall that archaeologists <em>love</em> to classify things…producing lots of variables that consist of counts (“abundance data”) and presence/absence observations (“incidence data”).</p>
<p>Enter <strong>Correspondence Analysis</strong>, which is analogous to PCA in examining the relationships between variables based on the cases/observations/rows available.</p>
<p>Shennan provides a stripped down example (Table 13.1) to illustrate the logic.</p>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb584-1"><a href="correspondence-analysis.html#cb584-1" tabindex="-1"></a>Table13<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/ShennanCh13_Table1.csv&quot;</span>, <span class="at">header=</span>T)</span>
<span id="cb584-2"><a href="correspondence-analysis.html#cb584-2" tabindex="-1"></a><span class="fu">kable</span>(Table13<span class="fl">.1</span>) <span class="sc">%&gt;%</span> kable_classic <span class="sc">%&gt;%</span> </span>
<span id="cb584-3"><a href="correspondence-analysis.html#cb584-3" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">&quot;float_right&quot;</span>)</span></code></pre></div>
<table class=" lightable-classic table" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; margin-left: auto; margin-right: auto; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:left;">
Assemblage
</th>
<th style="text-align:right;">
Microliths
</th>
<th style="text-align:right;">
Scrapers
</th>
<th style="text-align:right;">
Burins
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
136
</td>
<td style="text-align:right;">
95
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
234
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
690
</td>
<td style="text-align:right;">
181
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
897
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:right;">
165
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
262
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
1013
</td>
<td style="text-align:right;">
478
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:right;">
1550
</td>
</tr>
</tbody>
</table>
<p>If we want to compare assemblages to one another when they vary so much in size, it obviously makes a lot more sense to consider proportions - looking, as we have before, at both row and column proportions for different things. Shennan does this in Table 13.2; we can reproduce that, experimenting with <code>vegan::decostand</code> as an alternative to <code>addmargins</code>.</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="correspondence-analysis.html#cb585-1" tabindex="-1"></a>Table13<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">decostand</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">method=</span><span class="st">&quot;total&quot;</span>, <span class="at">MARGIN =</span> <span class="dv">1</span>), </span>
<span id="cb585-2"><a href="correspondence-analysis.html#cb585-2" tabindex="-1"></a>                   <span class="dv">2</span>) <span class="co">#row percents</span></span>
<span id="cb585-3"><a href="correspondence-analysis.html#cb585-3" tabindex="-1"></a>Table13<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">rbind</span>(Table13<span class="fl">.2</span>, <span class="fu">round</span>(<span class="fu">decostand</span>(Table13<span class="fl">.1</span>[<span class="dv">6</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">method=</span><span class="st">&quot;total&quot;</span>, </span>
<span id="cb585-4"><a href="correspondence-analysis.html#cb585-4" tabindex="-1"></a>                                              <span class="at">MARGIN =</span> <span class="dv">1</span>), <span class="dv">3</span>))</span>
<span id="cb585-5"><a href="correspondence-analysis.html#cb585-5" tabindex="-1"></a><span class="fu">rownames</span>(Table13<span class="fl">.2</span>)[<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Average&quot;</span></span>
<span id="cb585-6"><a href="correspondence-analysis.html#cb585-6" tabindex="-1"></a><span class="fu">kable</span>(Table13<span class="fl">.2</span>) <span class="sc">%&gt;%</span> <span class="fu">kable_minimal</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb585-7"><a href="correspondence-analysis.html#cb585-7" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">&quot;float_right&quot;</span>)</span></code></pre></div>
<table class=" lightable-minimal table" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; margin-left: auto; margin-right: auto; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Microliths
</th>
<th style="text-align:right;">
Scrapers
</th>
<th style="text-align:right;">
Burins
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
0.600
</td>
<td style="text-align:right;">
0.330
</td>
<td style="text-align:right;">
0.070
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
0.580
</td>
<td style="text-align:right;">
0.410
</td>
<td style="text-align:right;">
0.010
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
0.930
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.070
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
0.770
</td>
<td style="text-align:right;">
0.200
</td>
<td style="text-align:right;">
0.030
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
0.300
</td>
<td style="text-align:right;">
0.630
</td>
<td style="text-align:right;">
0.070
</td>
</tr>
<tr>
<td style="text-align:left;">
Average
</td>
<td style="text-align:right;">
0.654
</td>
<td style="text-align:right;">
0.308
</td>
<td style="text-align:right;">
0.038
</td>
</tr>
</tbody>
</table>
<p>CA hinges on something that is camouflaged in a table of proportions: the ‘average’ proportion in this table is <em>not</em> the mean of all the proportions. That is, the ‘Average’ row we’ve added at the bottom of Table 13.2 is not the mean of that column. Try it:</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="correspondence-analysis.html#cb586-1" tabindex="-1"></a><span class="fu">colMeans</span>(Table13<span class="fl">.2</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,])</span></code></pre></div>
<pre><code>## Microliths   Scrapers     Burins 
##      0.636      0.314      0.050</code></pre>
<p>The results aren’t <em>wildly</em> different, but they are different. The distinction is in whether each row should contribute equally to our assessment of the “average” lithic assemblage. Contrast, for instance, Assemblages 3 and 4:</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="correspondence-analysis.html#cb588-1" tabindex="-1"></a><span class="fu">kable</span>(Table13<span class="fl">.1</span>[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>,]) <span class="sc">%&gt;%</span> <span class="fu">kable_classic</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb588-2"><a href="correspondence-analysis.html#cb588-2" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">&quot;float_left&quot;</span>)</span></code></pre></div>
<table class=" lightable-classic table" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; margin-left: auto; margin-right: auto; width: auto !important; float: left; margin-right: 10px;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Assemblage
</th>
<th style="text-align:right;">
Microliths
</th>
<th style="text-align:right;">
Scrapers
</th>
<th style="text-align:right;">
Burins
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
690
</td>
<td style="text-align:right;">
181
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
897
</td>
</tr>
</tbody>
</table>
<p>If we are thinking of each assemblage as telling us something about lithic assemblages <em>in general</em>, then the 897 lithics from Assemblage 4 are surely telling us <em>more</em> than the 44 lithics from Assemblage 3.</p>
<p>As a result, we want to account for the size of each assemblage in considering its contribution to the overall average. We could calculate average column proportions that match those of Table 13.2 by using the table totals:</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="correspondence-analysis.html#cb589-1" tabindex="-1"></a>Table13<span class="fl">.1</span>[<span class="dv">6</span>,]</span></code></pre></div>
<pre><code>##   Assemblage Microliths Scrapers Burins Total
## 6      Total       1013      478     59  1550</code></pre>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="correspondence-analysis.html#cb591-1" tabindex="-1"></a><span class="dv">1013</span><span class="sc">/</span><span class="dv">1550</span></span></code></pre></div>
<pre><code>## [1] 0.6535484</code></pre>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="correspondence-analysis.html#cb593-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">as.matrix</span>(Table13<span class="fl">.1</span>[<span class="dv">6</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   Microliths  Scrapers     Burins
## 6  0.6535484 0.3083871 0.03806452</code></pre>
<p>We could <em>also</em> arrive at that number by weighting the proportion of each assemblage according to its size.</p>
<p>Consider the column proportions:</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="correspondence-analysis.html#cb595-1" tabindex="-1"></a>Table13<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">decostand</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">method=</span><span class="st">&quot;total&quot;</span>, <span class="at">MARGIN =</span> <span class="dv">2</span>), </span>
<span id="cb595-2"><a href="correspondence-analysis.html#cb595-2" tabindex="-1"></a>                   <span class="dv">2</span>) <span class="co">#col percents</span></span>
<span id="cb595-3"><a href="correspondence-analysis.html#cb595-3" tabindex="-1"></a>Table13<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Table13<span class="fl">.3</span>, <span class="fu">round</span>(<span class="fu">decostand</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">5</span>], <span class="at">method=</span><span class="st">&quot;total&quot;</span>, </span>
<span id="cb595-4"><a href="correspondence-analysis.html#cb595-4" tabindex="-1"></a>                                              <span class="at">MARGIN =</span> <span class="dv">2</span>), <span class="dv">2</span>))</span>
<span id="cb595-5"><a href="correspondence-analysis.html#cb595-5" tabindex="-1"></a><span class="fu">colnames</span>(Table13<span class="fl">.3</span>)[<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Average&quot;</span></span>
<span id="cb595-6"><a href="correspondence-analysis.html#cb595-6" tabindex="-1"></a><span class="fu">kable</span>(Table13<span class="fl">.3</span>) <span class="sc">%&gt;%</span> <span class="fu">kable_paper</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb595-7"><a href="correspondence-analysis.html#cb595-7" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">&quot;float_right&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:right;">
Microliths
</th>
<th style="text-align:right;">
Scrapers
</th>
<th style="text-align:right;">
Burins
</th>
<th style="text-align:right;">
Average
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.07
</td>
</tr>
<tr>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.15
</td>
</tr>
<tr>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.03
</td>
</tr>
<tr>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
0.58
</td>
</tr>
<tr>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
</tbody>
</table>
<p>These - the contributions of each assemblage to the total (i.e., of all the lithics, 58% are in Assemblage 4, and only 3% in Assemblage 3) - tell us how much each proportion should count in considering the total. So, if we multiply the proportion of microliths in each assemblage by the proportion of each assemblage in the total, and sum those:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="correspondence-analysis.html#cb596-1" tabindex="-1"></a><span class="fu">colSums</span>(Table13<span class="fl">.2</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,] <span class="sc">*</span> Table13<span class="fl">.3</span>[,<span class="dv">4</span>])</span></code></pre></div>
<pre><code>## Microliths   Scrapers     Burins 
##     0.6545     0.3077     0.0378</code></pre>
<p>So? This tells us that overall microliths make up ~65% of lithic assemblages, scrapers ~31%, and burins ~4%.</p>
<p>Because we are characterizing assemblages using three variables, we can visualize this with a ternary plot, as Shennan does in Figure 13.1.</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="correspondence-analysis.html#cb598-1" tabindex="-1"></a><span class="fu">TernaryPlot</span>(<span class="at">atip =</span> <span class="st">&quot;Microliths&quot;</span>, <span class="at">btip =</span> <span class="st">&quot;Scrapers&quot;</span>, <span class="at">ctip =</span> <span class="st">&quot;Burins&quot;</span>)</span>
<span id="cb598-2"><a href="correspondence-analysis.html#cb598-2" tabindex="-1"></a></span>
<span id="cb598-3"><a href="correspondence-analysis.html#cb598-3" tabindex="-1"></a><span class="fu">TernaryPoints</span>(Table13<span class="fl">.2</span>[,<span class="fu">c</span>(<span class="st">&quot;Microliths&quot;</span>, <span class="st">&quot;Scrapers&quot;</span>, <span class="st">&quot;Burins&quot;</span>)],</span>
<span id="cb598-4"><a href="correspondence-analysis.html#cb598-4" tabindex="-1"></a>              <span class="at">cex =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">16</span>,<span class="dv">5</span>), <span class="dv">8</span>))</span>
<span id="cb598-5"><a href="correspondence-analysis.html#cb598-5" tabindex="-1"></a></span>
<span id="cb598-6"><a href="correspondence-analysis.html#cb598-6" tabindex="-1"></a><span class="fu">TernaryText</span>(Table13<span class="fl">.2</span>[,<span class="fu">c</span>(<span class="st">&quot;Microliths&quot;</span>, <span class="st">&quot;Scrapers&quot;</span>, <span class="st">&quot;Burins&quot;</span>)] <span class="sc">+</span> .<span class="dv">025</span>, </span>
<span id="cb598-7"><a href="correspondence-analysis.html#cb598-7" tabindex="-1"></a>             <span class="fu">rownames</span>(Table13<span class="fl">.2</span>), <span class="at">cex =</span> <span class="dv">1</span>, <span class="at">font =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-217-1.png" width="672" /></p>
<p>In <em>weighting</em> each proportion by the size of each assemblage, we are considering the <em>mass</em> of a row: how much influence should that row (or column, this can be transposed) have on our thinking about the whole?</p>
<p>Correspondence analysis draws on this concept of mass, and on another familiar concept: expected values.
How different, we might ask, is any given assemblage from the average? A chi-square test, you’ll remember, calculates this by applying the average percents for each column to each row total, i.e., for the first assemblage:</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="correspondence-analysis.html#cb599-1" tabindex="-1"></a>Table13<span class="fl">.1</span>[<span class="dv">1</span>,<span class="dv">5</span>] <span class="sc">*</span> Table13<span class="fl">.2</span>[<span class="dv">6</span>,]</span></code></pre></div>
<pre><code>##         Microliths Scrapers Burins
## Average     73.902   34.804  4.294</code></pre>
<p>The simplest way to return these is just by running <code>chisq.test()</code> and using the expected values that are silently returned. This produces the values in parentheses in Shennan’s Table 13.4.</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="correspondence-analysis.html#cb601-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">chisq.test</span>(Table13<span class="fl">.1</span>[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])<span class="sc">$</span>expected, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##      Microliths Scrapers Burins Total
## [1,]       73.9     34.8    4.3   113
## [2,]      152.9     72.2    8.9   234
## [3,]       28.8     13.6    1.7    44
## [4,]      586.2    276.6   34.1   897
## [5,]      171.2     80.8   10.0   262
## [6,]     1013.0    478.0   59.0  1550</code></pre>
<p>We can also look at the chi-square results, which tell us that the table is not homogenous; it’s <em>very</em> unlikely that these assemblages came from comparable populations.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="correspondence-analysis.html#cb603-1" tabindex="-1"></a><span class="fu">chisq.test</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  Table13.1[1:5, 2:4]
## X-squared = 236.68, df = 8, p-value &lt; 2.2e-16</code></pre>
<p>We can <em>also</em> use the chi-squared results to consider the difference of each row (or column) that we have from from the hypothetical ‘average’ row (or column). In fact the chi-squared statistic is derived by calculating this for each row and summing the results.
If we divide that <span class="math inline">\(\chi^2\)</span> statistic by the sample size (here <span class="math inline">\(236.68/1550\)</span>), we get a measure of how much the observed values <em>in aggregate</em> depart from the expected values.
We can calculate that individually for each row (“How far do the observed values in Assemblage 1 depart from the expected values?”). We can also, following the logic we used for proportions above, then <em>weight</em> the distances for each row by the <em>mass</em> of each row. That is, we can ask how much Assemblage 1 should matter in our consideration of the whole, and answer the question by considering what proportion of the total it makes up ( <span class="math inline">\(113/1550 = .07\)</span> is the answer). The sum of the masses for each row is the <em>inertia</em> of the table.
The same can be done for columns!</p>
<p>The distance measures that we get - how far each row (or column) departs from the notional average - are the <em>chi-squared distances</em>, which are analogous to the Euclidean distances that we have used for comparing multivariate cases!</p>
<p>Since we only have three variables, we can transform these distances into Euclidean distances, and display them in three dimensions, as Shennan does in Figure 13.2.</p>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-221-1.png" width="672" /></p>
<p>Unfortunately, this only works because we have three variables to display, so only need three dimensions. With more variables, we run into the familiar problem of having brains that aren’t adequate for visualizing the multi-dimensional space that would be necessary.</p>
<p>Since upgrading those brains is probably a pipe dream, how can we <em>reduce</em> the dimensionality of these data?
- With PCA we could rely on correlations between variables to define space and positions in it; now positions are defined by chi-squared distances.
- As with PCA, however, we can think about the points as stretched out in certain dimensions, and we can fit lines through those dimensions. In CA, rather than that line accounting for variance, it accounts for inertia. <em>If there is a particular direction in which the weighted distances of the points are large, then an axis in that direction will account for most of the inertia in the data.</em>
- In another familiar approach, we can measure the deviations of each point from that line, and use the squares of those deviations to find a line of best fit. Doing this successively produces a series of axes that are equivalent to the principal components in PCA.</p>
<p>Ideally, CA will find 2-3 such axes that account for most of the inertia in the data…</p>
<p>To actually do this, we begin by calculating the contribution of each cell to the overall inertia (Shennan eventually gets around to this in Table 13.6).</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="correspondence-analysis.html#cb605-1" tabindex="-1"></a>chidist <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span> <span class="co">#chi-squared distances ^2</span></span>
<span id="cb605-2"><a href="correspondence-analysis.html#cb605-2" tabindex="-1"></a>chidist_table <span class="ot">&lt;-</span> <span class="fu">addmargins</span>(chidist) <span class="co">#row/column sum matches chi-squared statistic</span></span>
<span id="cb605-3"><a href="correspondence-analysis.html#cb605-3" tabindex="-1"></a>cell_inertia <span class="ot">&lt;-</span> <span class="fu">round</span>(chidist_table<span class="sc">/</span><span class="fu">sum</span>(chidist)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>)</span>
<span id="cb605-4"><a href="correspondence-analysis.html#cb605-4" tabindex="-1"></a></span>
<span id="cb605-5"><a href="correspondence-analysis.html#cb605-5" tabindex="-1"></a><span class="fu">kable</span>(cell_inertia) <span class="sc">%&gt;%</span> <span class="fu">kable_paper</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb605-6"><a href="correspondence-analysis.html#cb605-6" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">&quot;float_right&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Microliths
</th>
<th style="text-align:right;">
Scrapers
</th>
<th style="text-align:right;">
Burins
</th>
<th style="text-align:right;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:right;">
0.1
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
1.6
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
0.8
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
5.5
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
2.2
</td>
<td style="text-align:right;">
5.7
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:right;">
8.4
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
7.8
</td>
<td style="text-align:right;">
14.0
</td>
<td style="text-align:right;">
0.8
</td>
<td style="text-align:right;">
22.5
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
21.4
</td>
<td style="text-align:right;">
37.1
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
62.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Sum
</td>
<td style="text-align:right;">
32.4
</td>
<td style="text-align:right;">
59.9
</td>
<td style="text-align:right;">
7.7
</td>
<td style="text-align:right;">
100.0
</td>
</tr>
</tbody>
</table>
<p>This table gives the contributions of each cell, row, and column to the total inertia (i.e., departure from the expected values). It’s clear that Assemblage 5 has a much larger contribution than the other assemblages, and that scrapers contribute much more than the other types (in fact burins barely contribute at all). Why these differences? Relative size of assemblage (or type) + magnitude of departure from expected.</p>
<p>Total inertia and contributions to inertia form the basis for CA, which R will deliver using the <code>ca()</code> function from the <em>ca</em> package (among other ways).</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="correspondence-analysis.html#cb606-1" tabindex="-1"></a>Meso_ca <span class="ot">&lt;-</span> <span class="fu">ca</span>(Table13<span class="fl">.1</span>[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb606-2"><a href="correspondence-analysis.html#cb606-2" tabindex="-1"></a><span class="fu">summary</span>(Meso_ca)</span></code></pre></div>
<p>This table summarizes how well the CA axes account for each row and column (Shennan illustrates something similar in Table 13.7). It’s anchored in now-familiar numbers:</p>
<ul>
<li><em>Mass</em> is the contribution to inertia of each row and column, but out of 1000 rather than out of 100 (i.e., the row/column total divided by the entire sample size).<br />
</li>
<li><em>inr</em> is the distance of each row/column from the average, weighted by its mass as we just calculated above.</li>
<li>The <em>qlt</em> column is a measure of how much of the row and column variation can be described with the number of axes calculated (here two, which between them account for all the variation - so all the scores are 1000).</li>
<li>The <em>k</em> columns give the coordinates of the rows and columns on the two principal axes.</li>
<li>The <em>ctr</em> and <em>cor</em> columns associated with each <em>k</em> value tell us:
<ul>
<li>how much of the inertia in a row/column is accounted for by that axis (<em>cor</em>)</li>
<li>what proportion of the inertia accounted for by that axis is provided by that row/column (<em>ctr</em>)</li>
</ul></li>
</ul>
<p>This starts to seem a lot more useful when examined graphically (and more useful yet as the numbers of variables multiply). We can produce a close analogue of Shennan’s Figure 13.6, which plots the assemblages relative to the main dimensions of variation. Note that our plot is rotated 180º relative to Shennan’s, but if you examine where the assemblages plot relative to the variables, you’ll see the same pattern - assemblages basically vary along a microliths-scrapers axis, with burins having little influence.</p>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="correspondence-analysis.html#cb607-1" tabindex="-1"></a><span class="fu">plot</span>(Meso_ca, <span class="at">map =</span> <span class="st">&quot;rowprincipal&quot;</span>)</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-224-1.png" width="672" /></p>
<p>We can also - as Shennan does in Fig. 13.7 - look instead at where the lithic types plot in a space defined by the assemblages.</p>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="correspondence-analysis.html#cb608-1" tabindex="-1"></a><span class="fu">plot</span>(Meso_ca, <span class="at">map =</span> <span class="st">&quot;colprincipal&quot;</span>)</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-225-1.png" width="672" /></p>
<p><em>Or</em> - Shennan’s Fig. 13.8 - we can in effect overlay the spaces of these two plots by producing a symmetric scattergram (note Shennan’s cautions about interpreting this space, pp.323-324).</p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="correspondence-analysis.html#cb609-1" tabindex="-1"></a><span class="fu">plot</span>(Meso_ca, <span class="at">map =</span> <span class="st">&quot;symmetric&quot;</span>)</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-226-1.png" width="672" /></p>
<div id="an-archaeological-case-study-danish-bronze-age-hoards" class="section level2 hasAnchor" number="24.1">
<h2><span class="header-section-number">24.1</span> An Archaeological Case Study: Danish Bronze Age Hoards<a href="correspondence-analysis.html#an-archaeological-case-study-danish-bronze-age-hoards" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This starts to look a <em>lot</em> more interesting (and appealing) with datasets that are too big to grasp by simply eyeballing them. Shennan’s example is one of 63 Bronze Age hoards from Denmark.
<img src="Shennan_Table13-8.jpg" /></p>
<p>As you can imagine, the resulting CA table has a lot going on.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="correspondence-analysis.html#cb610-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;data/HoardsWide.RData&quot;</span>)</span>
<span id="cb610-2"><a href="correspondence-analysis.html#cb610-2" tabindex="-1"></a>hoards_ca <span class="ot">&lt;-</span> <span class="fu">ca</span>(HoardsWide, <span class="at">nd=</span><span class="dv">4</span>)</span></code></pre></div>
<p>There’s useful information there - to be discussed - but we’ll cut straight to generating the resulting plots.</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="correspondence-analysis.html#cb611-1" tabindex="-1"></a><span class="fu">plot</span>(hoards_ca, <span class="at">dim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>))</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-228-1.png" width="672" /></p>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="correspondence-analysis.html#cb612-1" tabindex="-1"></a><span class="fu">plot</span>(hoards_ca, <span class="at">dim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>))</span></code></pre></div>
<p><img src="Drennan_notes_files/figure-html/unnamed-chunk-229-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cluster-analysis-ch.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="what-next.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": false,
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
